# Render Blueprint - Complete Automated Deployment
# Just push this to GitHub and Render does EVERYTHING

services:
  # Your API Grader Service - FREE TIER
  - type: web
    name: api-grader-mcp
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free  # FREE TIER - spins down after 15 min idle
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: RATE_LIMIT
        value: 100
      - key: TEMPLATE_PATH
        value: /app/templates/MASTER_API_TEMPLATE_v3.yaml
      - key: API_KEYS
        value: '{"sk_prod_001": {"teamId": "team-alpha", "userId": "admin"}}'
      - key: DATABASE_URL
        fromDatabase:
          name: api-grader-db
          property: connectionString
    autoDeploy: true  # Auto-deploy on every git push
    healthCheckPath: /health
    region: oregon
    
databases:
  # PostgreSQL Database - FREE for 90 days
  - name: api-grader-db
    plan: free  # FREE for 90 days
    databaseName: apigrader
    user: apigrader
    postgresMajorVersion: 15
    region: oregon