#!/bin/bash

# RENDER DEPLOYMENT - FINAL AUTOMATED SETUP
# ==========================================

clear
echo "🚀 RENDER DEPLOYMENT - ALMOST THERE!"
echo "====================================="
echo ""
echo "✅ GitHub repo created: https://github.com/SmackdabDevOps/smackdab-api-grader"
echo "✅ Render CLI installed and authenticated"
echo "✅ render.yaml blueprint ready"
echo ""
echo "⚠️  Render requires a credit card (even for free tier)"
echo ""
echo "QUICK STEPS TO COMPLETE:"
echo "========================"
echo ""
echo "1. Add payment method (won't be charged for free tier):"
echo "   https://dashboard.render.com/billing"
echo ""
echo "2. Once card is added, run this command:"
echo ""
echo "   curl -X POST https://api.render.com/v1/services \\"
echo "     -H \"Authorization: Bearer rnd_41IqeFMzSxsHOwUvcSbyVBfvJTLB\" \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d @render-deploy.json"
echo ""
echo "OR"
echo ""
echo "3. Use Render Dashboard (EASIER):"
echo "   a. Go to: https://dashboard.render.com/"
echo "   b. Click 'New +' → 'Web Service'"
echo "   c. Connect GitHub account"
echo "   d. Select: SmackdabDevOps/smackdab-api-grader"
echo "   e. Render will auto-detect the render.yaml"
echo "   f. Click 'Create Web Service'"
echo ""
echo "THAT'S IT! Render will:"
echo "- Read render.yaml automatically"
echo "- Create PostgreSQL database"
echo "- Set all environment variables"
echo "- Deploy your app"
echo "- Give you a URL like: https://api-grader-mcp.onrender.com"
echo ""
echo "From then on, every 'git push' auto-deploys!"
